export { useHabitacion } from './useHabitacion.jsx';
export { usePostHabitacion } from './usePostHabitacion.jsx';
export { useLogin } from './useLogin.jsx';
export { useRegister } from './useRegister.jsx';
export {useReservacion} from './useReservacion.jsx';    
export {usePostReservacion} from './usePostReservacion.jsx';
export {useDeleteHabitacion} from './useDeleteHabitacion.jsx';
export {useEditHabitacion} from './useEditHabitacion.jsx';
export {useDeleteReservacion} from './useDeleteReservacion.jsx';
export {useUpdateReservacion} from './useUpdateReservacion.jsx';
