export * from './validateHabitacionCapacidad'
export * from './validateHabitacionNombre'
export * from './validateHabitacionPrecio'
export * from './validateHabitacionTipo'
export * from './validateHabitacionNumero'
export * from './validateHabitacionIdHotel'