export * from './validateEmail'
export * from './validatePassword'
export * from './validatePasswordCofirm'
export * from './validateHabitacionId'
export * from './validateFecha'
export * from './validateFechaFinAfterFechaInicio'